#
# Abstract NodeType for a Neos.Neos site.
# Each homepage must extend this NodeType.
# Nodes of this type must be direct children of the Neos.Neos:Site Root
# and must not be created at any other place in the tree.
#
'Neos.Neos:Site':
  abstract: true
  superTypes:
    'Neos.Neos:Document': true

  properties:
    name:
      scope: nodeAggregate
      type: string
    domains:
      scope: nodeAggregate
      type: references
      constraints:
        nodeTypes:
          Neos.Neos:Domain: true
    primaryDomain:
      scope: nodeAggregate
      type: reference
      constraints:
        nodeTypes:
          Neos.Neos:Domain: true
    siteResourcesPackageKey:
      scope: nodeAggregate
      type: string
    assetCollection:
      scope: nodeAggregate
      type: Neos\\Media\\Domain\\Model\\AssetCollection
